name: flutter_camera_ml_vision
description: A flutter widget that show the camera stream and allow ML vision recognition on it, it allow you to detect barcodes, labels, text, faces...
version: 1.5.0
authors:
  - Jimmy Aumard <jimmy.aumard@gmail.com>
  - Kevin Segaud <kevin@santetis.fr>
repository: https://github.com/santetis/flutter_camera_ml_vision
homepage: https://santetis.fr

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_ml_vision: ^0.7.0
  path_provider: ^0.5.0+1
  pedantic: ^1.4.0
  device_info: ^0.4.0+1
  camera: 
    git:
      url: https://github.com/jaumard/plugins
      ref: feature/camera_api_16_installation
      path: packages/camera

dev_dependencies:
  flutter_test:
    sdk: flutter
    