name: flutter_camera_ml_vision
description: A flutter widget that show the camera stream and emit event when a barcode is detected.
version: 1.0.0
author: Kevin Segaud <kevin@santetis.fr>
homepage: https://santetis.fr

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_ml_vision: ^0.7.0
  path_provider: ^0.5.0+1
  camera: ^0.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
    